# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: 
    weight: 10

  - name: About
    url: en/author/jaehyeoncha
    weight: 20
  - parent: About
    name: introduce
    url: en/author/jaehyeoncha
    weight: 20
  - parent: About
    name: Skills
    url: en/skills
    weight: 20

  - name: Experience
    url: en/experience
    weight: 30

  - name: Projects
    url: en/projects
    weight: 40

  - name: Contact
    url: en/contact
    weight: 50
